// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBacWmy0-lZ63si0JnI3iw9y2bqODlKC0w',
    appId: '1:595605164826:web:79a555b8b32d4313f7d2a3',
    messagingSenderId: '595605164826',
    projectId: 'todoapp-f3e0f',
    authDomain: 'todoapp-f3e0f.firebaseapp.com',
    storageBucket: 'todoapp-f3e0f.firebasestorage.app',
    measurementId: 'G-40MY541741',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTF1IOUjuW6jgyAOzurvX-MI7AOu_SmJ4',
    appId: '1:595605164826:android:08a8c8a986931897f7d2a3',
    messagingSenderId: '595605164826',
    projectId: 'todoapp-f3e0f',
    storageBucket: 'todoapp-f3e0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRC9krkpnfcEgcHQVA1sPgC2EvsGm4whQ',
    appId: '1:595605164826:ios:4f29b4f54542a2fbf7d2a3',
    messagingSenderId: '595605164826',
    projectId: 'todoapp-f3e0f',
    storageBucket: 'todoapp-f3e0f.firebasestorage.app',
    iosBundleId: 'com.example.todoBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRC9krkpnfcEgcHQVA1sPgC2EvsGm4whQ',
    appId: '1:595605164826:ios:4f29b4f54542a2fbf7d2a3',
    messagingSenderId: '595605164826',
    projectId: 'todoapp-f3e0f',
    storageBucket: 'todoapp-f3e0f.firebasestorage.app',
    iosBundleId: 'com.example.todoBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBacWmy0-lZ63si0JnI3iw9y2bqODlKC0w',
    appId: '1:595605164826:web:2952adef2c77c780f7d2a3',
    messagingSenderId: '595605164826',
    projectId: 'todoapp-f3e0f',
    authDomain: 'todoapp-f3e0f.firebaseapp.com',
    storageBucket: 'todoapp-f3e0f.firebasestorage.app',
    measurementId: 'G-ZQCVCCHV55',
  );
}
